### ISSUE TITLE
config gen is broken

### ISSUE THREAD

**Issue by bossman7309** [Nemesis-OS/nemesis-pkg#3]
bossman7398@fedora nemesis-pkg]$ sudo rm -rf /etc/nemesis-pkg
[bossman7398@fedora nemesis-pkg]$ sudo make install
echo "installing npkg-cfgen"
installing npkg-cfgen
install -Dm755 genconfig.py /usr/bin/npkg-cfgen
echo "installing nemesis-pkg"
installing nemesis-pkg
install -Dm755 main.py /usr/bin/npkg
install -Dm755 main.py /usr/bin/nemesis-pkg
mkdir /etc/nemesis-pkg
echo "note: please run npkg-cfgen to generate nemesis-pkg config"
note: please run npkg-cfgen to generate nemesis-pkg config
[bossman7398@fedora nemesis-pkg]$ npkg-cfgen
error: root user is needed to run this program
[bossman7398@fedora nemesis-pkg]$ sudo npkg-cfgen
note: checking if /etc/nemesis-pkg/config.py found..
note: fetching cpu flags.
sucess: cpu flags generated sucessfully
info: do you want to view cpu flags?[y/n] y
['cache:', '4', 'MiB', '(8', 'instances)']
note: making repositories..
info: release and security repository enabled..
note: would you like to enable community repo..[y/n] y
note: repository were configured
note: generating config file
note: config generated so saving it
sucess: config generated sucessfully

**Comment by abrik1** [comment]
hmm so this is a bug
